### PR TITLE
Fix config.yml

### PR DESCRIPTION
**Pull request by seunlanlege**
Also added the `CREATE2` deployer in the `genesis.json` and exposed ws server in geth.

### CODE REVIEW

**Comment by seunlanlege** [comment]
cc @kasey

**Comment by netzulo** [comment]
ty for the ENV `DENEB_FORK_VERSION` , i don't know why this PR it's not merged...

**Comment by rauljordan** [comment]
Hi @seunlanlege I integrated your changes into latest master. Thank you!

**Comment by netzulo** [comment]
NICE, ty @rauljordan  @seunlanlege !

**Pull request closed without merging**
